# Generated by Django 2.2.6 on 2019-10-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('str_grp', models.IntegerField(default=0)),
                ('code_order', models.IntegerField(default=0)),
                ('id_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=400)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Skill')),
            ],
        ),
    ]
