# Generated by Django 2.2.6 on 2019-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('file', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('approved_johanna', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='letter_value',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='range',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='skill',
            name='show_exercise_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='video_jump',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='englishskill',
            name='language',
            field=models.CharField(default='english', max_length=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='videos',
            field=models.ManyToManyField(to='app.Video'),
        ),
    ]
