# Generated by Django 2.2.6 on 2019-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191007_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishskill',
            name='language',
            field=models.CharField(default='EN', max_length=2),
        ),
    ]
