# Generated by Django 2.2.6 on 2019-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191007_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='videos',
            field=models.ManyToManyField(blank=True, to='app.Video'),
        ),
    ]
