# Generated by Django 2.2.6 on 2019-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191007_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
