# Generated by Django 2.2.6 on 2019-10-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191009_1324'),
    ]
    atomic = False
    operations = [
        migrations.CreateModel(
            name='EnglishElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='EN', max_length=2)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Element',
        ),
        migrations.DeleteModel(
            name='EnglishSkill',
        ),
        migrations.AddField(
            model_name='englishelement',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Element'),
        ),
    ]
