# Generated by Django 2.2.6 on 2019-10-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191011_1020'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='EnglishElement',
            new_name='ElementText',
        ),
    ]
