# Generated by Django 2.2.6 on 2019-10-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191011_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtext',
            name='author_note',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='elementtext',
            name='named',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='elementtext',
            name='short_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='elementtext',
            name='text',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
