# Generated by Django 2.2.6 on 2019-10-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191011_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementtext',
            old_name='author_note',
            new_name='additonal_info',
        ),
    ]
