# Generated by Django 2.2.6 on 2019-10-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191012_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementtext',
            old_name='additonal_info',
            new_name='additional_info',
        ),
    ]
