# Generated by Django 2.2.6 on 2019-10-12 22:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_usernotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotes',
            new_name='UserNote',
        ),
    ]
