# Generated by Django 2.2.6 on 2019-10-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191012_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='letter_value_67',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='element',
            name='letter_value_8',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='element',
            name='letter_value_9',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='element',
            name='value_67',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
        migrations.AddField(
            model_name='element',
            name='value_8',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
        migrations.AddField(
            model_name='element',
            name='value_9',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
        migrations.AddField(
            model_name='elementtext',
            name='hold_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='elementtext',
            name='id_number_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
