# Generated by Django 2.2.6 on 2019-10-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191016_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(blank=True, default='', max_length=30)),
                ('section', models.CharField(blank=True, default='', max_length=30)),
                ('rule_no', models.CharField(blank=True, default='', max_length=30)),
                ('sub_rule', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('additional_info', models.CharField(blank=True, default='', max_length=400)),
                ('rule_descriptions', models.CharField(blank=True, default='', max_length=400)),
                ('specific_deduction', models.CharField(blank=True, default='', max_length=400)),
                ('cat0', models.CharField(blank=True, default='', max_length=30)),
                ('cat1', models.CharField(blank=True, default='', max_length=30)),
                ('cat2', models.CharField(blank=True, default='', max_length=30)),
                ('cat3', models.CharField(blank=True, default='', max_length=30)),
                ('cat4', models.CharField(blank=True, default='', max_length=30)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Rule')),
            ],
        ),
    ]
