# Generated by Django 2.2.6 on 2019-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191023_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='display_order',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rule',
            name='search_display',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='element',
            name='letter_value',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='element',
            name='letter_value_67',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='element',
            name='letter_value_8',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='element',
            name='letter_value_9',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='value_67',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='value_8',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='value_9',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3),
        ),
        migrations.AlterField(
            model_name='rule',
            name='event',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
