# Generated by Django 2.2.6 on 2019-11-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191025_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawnImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=255)),
                ('label', models.TextField(blank=True, default='', max_length=255)),
                ('event', models.TextField(blank=True, default='', max_length=2)),
            ],
        ),
    ]
