# Generated by Django 2.2.6 on 2019-11-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_drawnimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrawnImages',
            new_name='DrawnImage',
        ),
    ]
