# Generated by Django 2.2.6 on 2019-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191104_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawnimage',
            name='event',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='drawnimage',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='drawnimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
