# Generated by Django 2.2.6 on 2019-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191108_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletext',
            name='chapter_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ruletext',
            name='section_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
