# Generated by Django 2.2.7 on 2019-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191120_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sent', models.TextField(blank=True, default='')),
            ],
        ),
    ]
