# Generated by Django 2.2.7 on 2019-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
