# Generated by Django 2.2.7 on 2019-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
