# Generated by Django 2.2.7 on 2019-11-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191130_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
