# Generated by Django 2.2.7 on 2019-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_subscription_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_payment',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
