# Generated by Django 2.2.7 on 2019-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191130_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_plan_id', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=10)),
                ('interval', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
