# Generated by Django 2.2.8 on 2019-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='action',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action_details',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
