# Generated by Django 2.2.8 on 2019-12-16 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_auto_20191211_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensive', models.BooleanField(default=False)),
                ('dont_need', models.BooleanField(default=False)),
                ('different_features', models.BooleanField(default=False)),
                ('low_quality', models.BooleanField(default=False)),
                ('hard_to_use', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('other_details', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
