# Generated by Django 2.2.8 on 2019-12-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20191223_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, default='', max_length=40)),
                ('category_order', models.IntegerField(default=0, max_length=1)),
                ('deduction_amount', models.IntegerField(default=0)),
                ('connected_elements', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default='', max_length=1)),
                ('event', models.CharField(blank=True, default='', max_length=2)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='VideoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(default=0)),
                ('skip_frame', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=12)),
                ('event', models.CharField(blank=True, default='', max_length=2)),
                ('cr', models.CharField(blank=True, default='', max_length=6)),
                ('override_text', models.CharField(blank=True, default='', max_length=255)),
                ('no_value_type', models.CharField(blank=True, default='', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('element_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Element')),
                ('rule_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.RuleLink')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Video')),
            ],
        ),
    ]
