# Generated by Django 2.2.8 on 2019-12-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20191230_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonote',
            name='element_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Element'),
        ),
        migrations.AlterField(
            model_name='videonote',
            name='rule_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.RuleLink'),
        ),
    ]
