# Generated by Django 2.2.8 on 2020-01-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_pagetour_usertourscomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNoteTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(default=0)),
                ('skip_frame', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=12)),
                ('event', models.CharField(blank=True, default='', max_length=2)),
                ('cr', models.CharField(blank=True, default='', max_length=6)),
                ('override_text', models.CharField(blank=True, default='', max_length=255)),
                ('no_value_type', models.CharField(blank=True, default='', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('element_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Element')),
                ('rule_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.RuleLink')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Video')),
            ],
        ),
    ]
