# Generated by Django 2.2.8 on 2020-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200120_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='down_value_letter',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='element',
            name='up_value_letter',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
