# Generated by Django 2.2.8 on 2020-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_videolink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.IntegerField(default=25),
        ),
    ]
