# Generated by Django 2.2.8 on 2020-02-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200203_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='video_jump',
        ),
        migrations.RemoveField(
            model_name='element',
            name='videos',
        ),
    ]
