# Generated by Django 2.2.8 on 2020-02-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20200212_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disc',null=True),
        ),
    ]
