# Generated by Django 2.2.8 on 2020-02-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_element_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='drawnimage',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='symbolduplicate',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='video',
            name='disc',
        ),
        migrations.AlterField(
            model_name='element',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
    ]
