# Generated by Django 2.2.8 on 2020-02-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200212_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
        migrations.AddField(
            model_name='drawnimage',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
        migrations.AddField(
            model_name='rule',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
        migrations.AddField(
            model_name='symbolduplicate',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
        migrations.AddField(
            model_name='video',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc'),
        ),
    ]
