# Generated by Django 2.2.8 on 2020-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20200212_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='event_list',
            field=models.CharField(default='V,UB,BB,FX', max_length=255),
        ),
        migrations.AddField(
            model_name='disc',
            name='full_name',
            field=models.CharField(default='Womens', max_length=25),
        ),
    ]
