# Generated by Django 2.2.8 on 2020-02-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20200217_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonote',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Video'),
        ),
    ]
