# Generated by Django 2.2.8 on 2020-02-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20200221_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='value_67',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='value_8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='value_9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
