# Generated by Django 2.2.8 on 2020-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20200221_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='old_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='old_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
