# Generated by Django 2.2.8 on 2020-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20200221_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='old_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
