# Generated by Django 2.2.8 on 2020-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_rule_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulelink',
            name='rule',
        ),
        migrations.AddField(
            model_name='rulelink',
            name='rule',
            field=models.ManyToManyField(to='app.Rule'),
        ),
    ]
