# Generated by Django 2.2.8 on 2020-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_rulelink_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulelink',
            name='old_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
