# Generated by Django 2.2.8 on 2020-02-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_rulelink_old_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnratedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('old_id', models.IntegerField(default=None, null=True)),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc')),
            ],
        ),
    ]
