# Generated by Django 2.2.8 on 2020-02-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_unratedelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonote',
            name='unrated_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UnratedElement'),
        ),
    ]
