# Generated by Django 2.2.8 on 2020-03-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_versionsettings_rule_sub_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionsettings',
            name='rule_sub_header',
            field=models.CharField(blank=True, default='Section', max_length=30),
        ),
    ]
