# Generated by Django 2.2.8 on 2020-03-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20200302_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, default='', max_length=2)),
                ('group', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Disc')),
            ],
        ),
    ]
