# Generated by Django 2.2.8 on 2020-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_structuregroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionsettings',
            name='drawing_prefix',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
