# Generated by Django 2.2.8 on 2020-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20200311_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='competitiongroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
