# Generated by Django 2.2.8 on 2020-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20200311_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='vault_range_high',
            field=models.DecimalField(decimal_places=1, default=10.1, max_digits=3),
        ),
        migrations.AddField(
            model_name='disc',
            name='vault_range_low',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
    ]
