# Generated by Django 2.2.8 on 2020-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20200313_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionsettings',
            name='use_level_slider',
            field=models.BooleanField(default=True),
        ),
    ]
