# Generated by Django 2.2.11 on 2020-03-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20200318_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionsettings',
            name='competition_videos',
        ),
        migrations.RemoveField(
            model_name='versionsettings',
            name='tcexamples',
        ),
    ]
