# Generated by Django 2.2.11 on 2020-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_tcexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcexample',
            name='special_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
