# Generated by Django 2.2.11 on 2020-03-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_tcexample_special_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=1)),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc')),
            ],
        ),
    ]
