# Generated by Django 2.2.11 on 2020-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_judgeinstruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videonote',
            options={'ordering': ['-video__id']},
        ),
        migrations.AddField(
            model_name='disc',
            name='show_login',
            field=models.BooleanField(default=False),
        ),
    ]
