# Generated by Django 2.2.11 on 2020-04-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_video_extra_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonotetemp',
            name='unrated_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UnratedElement'),
        ),
    ]
