# Generated by Django 2.2.11 on 2020-04-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_videonotetemp_unrated_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='approved',
            new_name='approved_final',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='approved_johanna',
            new_name='approved_liason',
        ),
    ]
