# Generated by Django 2.2.11 on 2020-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20200422_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='approved_sts',
            field=models.BooleanField(default=False),
        ),
    ]
