# Generated by Django 2.2.11 on 2020-05-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_rulelink_pause_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrampElementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_position', models.CharField(blank=True, default='', max_length=1)),
                ('flips', models.IntegerField(default=0)),
                ('twists', models.IntegerField(default=0)),
                ('start_position', models.CharField(blank=True, default='', max_length=5)),
                ('end_position', models.CharField(blank=True, default='', max_length=5)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Element')),
            ],
        ),
    ]
