# Generated by Django 2.2.11 on 2020-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_trampelementinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='tramp_body_position',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='element',
            name='tramp_end_position',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='element',
            name='tramp_flips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='tramp_start_position',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='element',
            name='tramp_twists',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TrampElementInfo',
        ),
    ]
