# Generated by Django 2.2.6 on 2020-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20200508_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='rule',
            name='section',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sub_rule',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
