# Generated by Django 2.2.6 on 2020-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20200508_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruletext',
            name='cat0',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ruletext',
            name='cat1',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ruletext',
            name='cat2',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ruletext',
            name='cat3',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ruletext',
            name='cat4',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
