# Generated by Django 2.2.6 on 2020-05-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20200508_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulelink',
            name='event',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
