# Generated by Django 2.2.6 on 2020-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20200508_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='exclude_screens',
            field=models.TextField(blank=True, default=''),
        ),
    ]
