# Generated by Django 2.2.6 on 2020-05-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_disc_exclude_screens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoachInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code_order', models.IntegerField(default=0)),
                ('development', models.TextField(blank=True, default='')),
                ('physical', models.TextField(blank=True, default='')),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc')),
                ('environment', models.ManyToManyField(to='app.CoachEnvironment')),
            ],
        ),
        migrations.CreateModel(
            name='CoachMethodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoachVideoLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('display_order', models.IntegerField(default=0)),
                ('instruction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CoachInstruction')),
            ],
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='methodology',
            field=models.ManyToManyField(to='app.CoachMethodology'),
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='pre_req_elements',
            field=models.ManyToManyField(related_name='_coachinstruction_pre_req_elements_+', to='app.CoachInstruction'),
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='related_elements',
            field=models.ManyToManyField(related_name='_coachinstruction_related_elements_+', to='app.CoachInstruction'),
        ),
    ]
