# Generated by Django 2.2.6 on 2020-05-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20200520_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinstruction',
            name='environment',
            field=models.ManyToManyField(blank=True, to='app.CoachEnvironment'),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='methodology',
            field=models.ManyToManyField(blank=True, to='app.CoachMethodology'),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='pre_req_elements',
            field=models.ManyToManyField(blank=True, related_name='_coachinstruction_pre_req_elements_+', to='app.CoachInstruction'),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='related_elements',
            field=models.ManyToManyField(blank=True, related_name='_coachinstruction_related_elements_+', to='app.CoachInstruction'),
        ),
    ]
