# Generated by Django 2.2.6 on 2020-05-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20200520_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachinstruction',
            old_name='code_order',
            new_name='display_order',
        ),
    ]
