# Generated by Django 2.2.6 on 2020-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_auto_20200520_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachinstruction',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='notes1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='notes2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='notes3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='coachinstruction',
            name='short_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
