# Generated by Django 2.2.6 on 2020-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20200522_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachinstruction',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
