# Generated by Django 2.2.6 on 2020-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_coachinstruction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
