# Generated by Django 2.2.6 on 2020-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_auto_20200522_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='notes3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
