# Generated by Django 2.2.6 on 2020-05-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_auto_20200522_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachvideoline',
            options={'ordering': ['display_order']},
        ),
        migrations.CreateModel(
            name='CoachVideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('frame_jump', models.IntegerField(default=0)),
                ('coach_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoachInstruction')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
