# Generated by Django 2.2.6 on 2020-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_coachvideolink_frame_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachenvironment',
            name='text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='coachmethodology',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
