# Generated by Django 2.2.6 on 2020-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_auto_20200528_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmethodology',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
