# Generated by Django 2.2.6 on 2020-05-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_auto_20200528_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachenvironment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='coachinstruction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='coachmethodology',
            options={'ordering': ['id']},
        ),
    ]
