# Generated by Django 2.2.6 on 2020-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_auto_20200529_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinstruction',
            name='pre_req_elements',
            field=models.ManyToManyField(blank=True, related_name='post_req_elements', to='app.CoachInstruction'),
        ),
        migrations.AlterField(
            model_name='coachinstruction',
            name='related_elements',
            field=models.ManyToManyField(blank=True, to='app.CoachInstruction'),
        ),
    ]
