# Generated by Django 2.2.6 on 2020-06-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_coachrules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachRules',
        ),
    ]
