# Generated by Django 2.2.6 on 2020-06-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_delete_coachrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachFundamentalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CoachFundamentalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoachFundamentalCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CoachFundamentalSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('interaction_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('MS', 'Multi Select'), ('T', 'Text Input'), ('N', 'None')], default='N', max_length=2)),
                ('interaction_prompt', models.CharField(blank=True, default='', max_length=400)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoachFundamentalSection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CoachFundamentalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('response_text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CoachFundamentalSlide')),
            ],
        ),
    ]
