# Generated by Django 2.2.6 on 2020-06-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_coachfundamentalanswer_coachfundamentalcategory_coachfundamentalsection_coachfundamentalslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachfundamentalcategory',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='coachfundamentalsection',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='coachfundamentalcategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachfundamentalsection',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
