# Generated by Django 2.2.6 on 2020-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_coachfundamentaluseranswer_coachfundamentaluserprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfundamentalslide',
            name='interaction_random_order',
            field=models.BooleanField(default=True),
        ),
    ]
