# Generated by Django 2.2.6 on 2020-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_coachusernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='skill_grp',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
