# Generated by Django 2.2.6 on 2020-07-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_element_skill_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcroBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('category', models.IntegerField(default=0)),
                ('skill_number', models.IntegerField(default=0)),
                ('value2', models.IntegerField(default=0)),
                ('value3', models.IntegerField(default=0)),
                ('value4', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('transition_bonus', models.CharField(blank=True, default='', max_length=12)),
                ('skill_name', models.CharField(blank=True, default='', max_length=255)),
                ('skill_description', models.CharField(blank=True, default='', max_length=255)),
                ('orientation', models.CharField(blank=True, default='', max_length=1)),
                ('layer', models.CharField(blank=True, default='', max_length=3)),
                ('base_box_number', models.IntegerField(default=0)),
                ('transition_group', models.CharField(blank=True, default='', max_length=3)),
                ('top_bottom', models.CharField(blank=True, default='', max_length=1)),
                ('top_interface_point', models.CharField(blank=True, default='', max_length=5)),
                ('bottom_interface_point', models.CharField(blank=True, default='', max_length=5)),
                ('bottom_interface_point2', models.CharField(blank=True, default='', max_length=5)),
                ('special_base_number', models.IntegerField(default=0)),
                ('base_number', models.CharField(blank=True, default='', max_length=5)),
                ('page_number', models.IntegerField(default=0)),
                ('thumbnail_direction', models.CharField(blank=True, default='', max_length=1)),
                ('start_number', models.CharField(blank=True, default='', max_length=60)),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Disc')),
            ],
        ),
    ]
