# Generated by Django 2.2.6 on 2020-07-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_acrobalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrobalance',
            name='disc',
        ),
    ]
