# Generated by Django 2.2.6 on 2020-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20200708_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcroWomensBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_interface', models.CharField(blank=True, default='', max_length=10)),
                ('top_interface', models.CharField(blank=True, default='', max_length=10)),
                ('bonus', models.IntegerField(default=0)),
                ('bonus_extra', models.IntegerField(default=0)),
            ],
        ),
    ]
