# Generated by Django 2.2.6 on 2020-07-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_auto_20200724_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrobalance',
            name='old_id',
        ),
    ]
