# Generated by Django 2.2.6 on 2020-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_remove_acrobalance_old_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcroBalanceTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_balance', models.CharField(max_length=4)),
                ('second_balance', models.CharField(max_length=4)),
                ('movement_value', models.IntegerField(default=0)),
                ('movement_value_hs_fs', models.IntegerField(default=0)),
                ('movement_value2', models.IntegerField(default=0)),
                ('movement_value3', models.IntegerField(default=0)),
                ('movement_value4', models.IntegerField(default=0)),
                ('table_number', models.IntegerField(default=0)),
                ('base_turn_180', models.IntegerField(default=0)),
                ('base_turn_180_hs', models.IntegerField(default=0)),
                ('base_turn_360', models.IntegerField(default=0)),
                ('base_turn_360_hs', models.IntegerField(default=0)),
            ],
        ),
    ]
