# Generated by Django 2.2.6 on 2020-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_acrobalancetransition_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrobalance',
            name='legs_together_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
