# Generated by Django 2.2.6 on 2020-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_acrobalance_legs_together_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcroMounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=2)),
                ('category', models.IntegerField(default=0)),
                ('mount', models.CharField(max_length=12)),
                ('base', models.CharField(blank=True, default='', max_length=12)),
                ('top', models.CharField(blank=True, default='', max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(default=0)),
            ],
        ),
    ]
