# Generated by Django 2.2.6 on 2020-08-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_acromounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcroMounts',
            new_name='AcroMount',
        ),
    ]
