# Generated by Django 2.2.6 on 2020-08-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_auto_20200810_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acromount',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mount_base', to='app.AcroBalance'),
        ),
        migrations.AlterField(
            model_name='acromount',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mount_top', to='app.AcroBalance'),
        ),
    ]
